# Generated by Django 2.2.10.dev20200615134759 on 2020-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='hash_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
