# Generated by Django 2.2.10 on 2020-07-17 19:39

from django.db import migrations, models
import saver.utils


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0002_auto_20200717_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='f',
            field=models.FileField(upload_to=saver.utils.custom_upload_path),
        ),
        migrations.AlterField(
            model_name='pack',
            name='hash_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
